[pytest]
testpaths = tests
addopts =
    -p no:ament_lint
    -p no:launch_pytest
    -p no:ament_pep257
    -p no:ament_copyright
    -p no:ament_xmllint
    -p no:launch_testing
    -p no:launch_ros
    -p no:ament_flake8
    -p no:ament_mypy

